version: 0.0 # codedeploy version, 다른버전 사용시 오류발생
os: linux
files:
  - source: / # codedeploy가 전달한 파일 중 destination 이동 대상 지정
    destination: /home/ec2-user/app/step2/zip/ # source에 지정된 파일을 받을 위치
    overwrite: yes # overwrite 옵션

# Codedeploy에서 EC2서버로 넘겨준 파일들 모두 ec2-user 권한을 갖도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# 배포단계에서 실행할 명령어 지정
hooks:
  ApplicationStart: # start 단계에서 수행
    - location: deploy.sh # deploy.sh을
      timeout: 60 # 스크립트 수행시간 60초 이내에
      runas: ec2-user # ec2-user 권한으로 실행